clean:
	@rm -f */*.o
	@rm -f */simulator */.psuade_mars */psuadeMetisInfo */psuadeGMetisInfo
	@rm -f */*/simulator
	@rm -f */psuadeData*
	@rm -f */*/psuadeData*
	@rm -f */psuadeApps_ct.*
	@rm -f */*/psuadeApps_ct.*

