name: Build Conda package

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize

defaults:
  run:
    # the -l flag is needed for the Conda environment to be activated properly
    shell: bash -l {0}

jobs:
  conda-build:
    name: Build Conda package (${{ matrix.os }})
    runs-on: ${{ matrix.os-runner }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - linux
          - macos
          - windows
        include:
          - os: linux
            os-runner: ubuntu-20.04
            artifact-upload-path: /usr/share/miniconda/envs/build-psuade/conda-bld/linux-64/psuade-lite-*.tar.bz2
          - os: macos
            os-runner: macos-latest
            artifact-upload-path: /usr/local/miniconda/envs/build-psuade/conda-bld/osx-64/psuade-lite-*.tar.bz2
          - os: windows
            os-runner: windows-2019
            artifact-upload-path: C:\Miniconda\envs\build-psuade\conda-bld\win-64\psuade-lite-*.tar.bz2
    steps:
      - uses: actions/checkout@v2
      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: build-psuade
          channels: conda-forge
      - name: Run conda-build
        working-directory: .conda-build
        run: |
          echo '::group::Output of "conda install/list"'
          conda install --quiet --yes conda-build
          conda list
          echo '::endgroup::'
          conda-build .
      - name: Save built package as downloadable artifact
        uses: actions/upload-artifact@v2
        with:
          name: psuade-lite-${{ matrix.os }}
          path: ${{ matrix.artifact-upload-path }}
          if-no-files-found: error
